services:

  redis:
    image: redis:alpine

  sqli:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - redis
    ports:
      - 8080:8080
    command: |
      python run.py
