# db:
#   user: postgres
#   password: postgres
#   host: postgres
#   port: 5432
#   database: sqli

# redis:
#   host: redis
#   port: 6379
#   db: 0

# app:
#   host: 0.0.0.0
#   port: 8080

db:
  user: avnadmin
  password: AVNS_Jf7LEmEPB3zrxmJbuNa
  host: pg-55824aba-9abc-468e-9a79-20a439eae39a-sqli1255708081-choreo-o.g.aivencloud.com
  port: 19605
  database: sqli

redis:
  host: redis
  port: 6379
  db: 0

app:
  host: 0.0.0.0
  port: 8080
